version: "3"

tasks:
  check:format:
    desc: "Check formatting with Ruff"
    cmd: uv run ruff format --check {{.CLI_ARGS}}

  fix:format:
    desc: "Fix formatting with Ruff"
    cmd: uv run ruff format {{.CLI_ARGS}}

  check:lint:
    desc: "Linting with Ruff"
    cmd: uv run ruff check {{.CLI_ARGS}}

  fix:lint:
    desc: "Fix linting with Ruff"
    cmd: uv run ruff check --fix {{.CLI_ARGS}}

  check:types:
    desc: "Type checking with basedpyright"
    cmd: uv run basedpyright {{.CLI_ARGS}}

  check:tests:
    desc: "Testing with pytest"
    vars:
      COVERAGE: "{{.COVERAGE | default false}}"
      MATRIX: "{{.MATRIX | default false}}"
      COV_ARGS: '{{if eq .COVERAGE "true"}}--cov=src --cov-report=term-missing{{end}}'
    cmds:
      - task: '{{if eq .MATRIX "true"}}check:tests:_matrix{{else}}check:tests:_single{{end}}'
        vars:
          COV_ARGS: "{{.COV_ARGS}}"

  check:tests:_single:
    internal: true
    cmd: uv run pytest {{.COV_ARGS}} {{.CLI_ARGS}}

  check:tests:_matrix:
    internal: true
    cmds:
      - for:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
        cmd: uv run -p {{.ITEM}} pytest {{.COV_ARGS}} {{.CLI_ARGS}}

  check:
    desc: "Run all checks"
    vars:
      COVERAGE: "{{.COVERAGE | default false}}"
      MATRIX: "{{.MATRIX | default false}}"
    cmds:
      - task: check:format
      - task: check:lint
      - task: check:types
      - task: check:tests
        vars:
          COVERAGE: "{{.COVERAGE}}"
          MATRIX: "{{.MATRIX}}"

  fix:
    desc: "Run all fixes"
    cmds:
      - task: fix:format
      - task: fix:lint
